export interface ParsedNote {
  title: string;
  body: string; // full text minus the trailing tag line, trimmed
  tags: string[]; // lowercased, trimmed, de-duplicated; [] if none
}

export interface Note extends ParsedNote {
  id: string; // generated, e.g. crypto.randomUUID()
  rawText: string; // exactly what the user typed, unmodified
  createdAt: string; // ISO 8601
  updatedAt: string; // ISO 8601
}

/**
 * A note as found in an imported file. `id`, `createdAt`, and `updatedAt`
 * are optional so hand-edited or older export files can still be imported;
 * missing values are generated by `NoteStore.importAll`. `title`, `body`,
 * and `tags` are ignored on import and re-derived from `rawText`.
 */
export interface ImportableNote {
  id?: string;
  rawText: string;
  createdAt?: string;
  updatedAt?: string;
}

export interface NoteStore {
  list(): Promise<Note[]>;
  get(id: string): Promise<Note | undefined>;
  create(rawText: string): Promise<Note>;
  update(id: string, rawText: string): Promise<Note>;
  remove(id: string): Promise<void>;
  listTags(): Promise<string[]>; // distinct tags across all notes, sorted
  listByTag(tag: string): Promise<Note[]>;
  /** Upserts each note by `id` (overwriting any existing note with the same id). */
  importAll(notes: ImportableNote[]): Promise<void>;
}
